#!/bin/bash
set -e # Exit with nonzero exit code if anything fails
TRAVIS_PULL_REQUEST="true"
function build() {
	npm run gulp
}
# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
if [ "$TRAVIS_PULL_REQUEST" != "false" -o ]; then
    echo "Skipping deploy; just doing a build."
    build
    exit 0
fi
# let's go back from Travis auto-generated branch to out target branch for publishing
git checkout master
# run our build process
build
# check if there are changes generated by build
if [[ `git status --porcelain` ]]; then
	echo "There are changes to publish!"
	git status
	git add .
	git remote add deployment https://${USER}:${PASSWORD}@github.com/${TRAVIS_REPO_SLUG}.git
	git config user.name "Travis CI"
	git commit -m "Travis CI $TRAVIS_COMMIT [skip ci]"
	git push -u deployment master
# if no changes generated by build
else
	echo "No changes to the output on this push; exiting."
    exit 0
fi
